### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by sfw2327** [xan105/Aion-Launcher#1]
Can you give me the license for this repository?  I am unable to locate it.  If there is not one, would you consider adding a permissive license?

**Comment by xan105** [comment]
Hmm I'm not *really* familiar with these things 😅.
I added to this project what https://choosealicense.com/ recommended me : 
`GNU Lesser General Public License v3.0`

Hope it's permissive enough for you.
Regards.

**Comment by BMillsVT** [comment]
@xan105 Would you consider the BSD or MIT license.  My company won't let us use GPL without an exception.

**Comment by xan105** [comment]
I'm sorry but I would only use MIT license for smaller projects or libraries.
